name: PVS-Studio analyze changes
on:
  push:
    paths:
      - '**.h'
      - '**.c'
      - '**.cpp'
  workflow_dispatch:

jobs:
  analyze-changes:
    runs-on: ubuntu-22.04
    steps:
      - name: Install tools
        run: |
          wget -qO- https://wcdn.pvs-studio.com/etc/pubkey.txt | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/viva64.gpg
          sudo wget -O /etc/apt/sources.list.d/viva64.list https://wcdn.pvs-studio.com/etc/viva64.list

          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends build-essential cmake curl libcurl4-openssl-dev pvs-studio

          pvs-studio-analyzer credentials ${{ secrets.PVS_STUDIO_CREDENTIALS }}

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Get list of changed source files
        run: |
          echo "$(git diff --name-only \
            ${{ github.event.before }}..${{ github.event.after }})" > source-files.txt
          cat source-files.txt

      - name: Build
        run: |
          cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=On -B build .
          cmake --build build -j

      - name: Analyze and generate report
        run: |
          if [ -s source-files.txt ]; then
            pvs-studio-analyzer analyze -f build/compile_commands.json --exclude-path 'build/_deps/' \
              --disableLicenseExpirationCheck -S source-files.txt -j

            plog-converter PVS-Studio.log -t json -n relative -R toRelative -r $PWD
            plog-converter relative.json -t sarif -n pvs-report -r file://
          else
            echo "No source files changed, skipping analysis"
            exit 0
          fi

      - name: Publish report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pvs-report.sarif
          category: PVS-Studio
